---
title: Knowledge pipeline
---
flowchart LR
    Articles --> check{Check}
    Podcasts --> check{Check}
    Books --> check{Check}
    Misc["Other Sources"] --> check{Check}
    check{Check} -->|Valuable| consume{Consume}
    check{Check} -->|Not valuable| d1["Discard it"]

    consume{Consume} -->|Valuable| capture{Capture}
    consume{Consume} -->|Not valuable| d2["Discard it"]

    capture{Capture} -->|Plugin / Kindle / App| ts[(Thought Saver)]
    capture{Capture} -->|Links / Notes| no[(Notion)]
